name: nnez_yisu
description: A Flutter canteen card assistant for NNEZ.
publish_to: 'none'
version: 2.4.2+202607183

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  home_widget: ^0.7.0
  intl: ^0.20.2
  open_filex: ^4.7.0
  package_info_plus: ^8.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  url_launcher: ^6.3.1
  workmanager: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/onesu.png
  adaptive_icon_foreground: assets/icons/onesu.png
  adaptive_icon_background: "#F5F0E6"
